# Generated by Django 4.2.10 on 2024-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='full_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_status',
            field=models.CharField(default='paid', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='phone',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
