# Generated by Django 4.2.10 on 2024-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hotelbooking_email_hotelbooking_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
