# Generated by Django 4.2.10 on 2024-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hotelbooking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
