# Generated by Django 4.2.10 on 2024-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_hotelbooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
